In [134]:
import pandas as pd



In [39]:
#Q1:Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module
df = pd.Series([1,2,3,4,5])
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
#Q2:Write a Pandas program to convert a Panda module Series to Python list and it's type

list1=[]
for i in df:
    list1.append(i)

print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [43]:
# Another Way 

listFromDframe= df.tolist()
print(listFromDframe)
print(type(listFromDframe))

[1, 2, 3, 4, 5]
<class 'list'>


In [44]:
#Q3:Write a Pandas program to add, subtract, multiple and divide two Pandas Series

s1= pd.Series([1,2,3,4,5])
s2=pd.Series([1,2,3,4,5])

print("Original Series S1", s1 )
print('\n')
print("Original Series S2",s2)

Original Series S1 0    1
1    2
2    3
3    4
4    5
dtype: int64


Original Series S2 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [53]:
#Multiplication
print('Multiplication')
print(s1*s2)
print('\n')
print('Addition')
print(s1+s2)
print('\n')
print('Division')
print(s1/s2)
print('\n')

Multiplication
0    1 
1    4 
2    9 
3    16
4    25
dtype: int64


Addition
0    2 
1    4 
2    6 
3    8 
4    10
dtype: int64


Division
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64




In [56]:
#Q4:Write a Pandas program to compare the elements of the two Pandas Series. 

s1= pd.Series([23,45,67,89])

s2= pd.Series([3,45,63,98])

print('comparing two Series::')

print(s1 == s2)

comparing two Series::
0    False
1    True 
2    False
3    False
dtype: bool


In [92]:
#Q5:Write a Pandas program to convert a dictionary to a Pandas series.

dict1 = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

s1= pd.DataFrame.from_dict(dict1,orient='index',columns=['A'])  # Set Orient = 'index' to use keys of dict1 as index
s1

# pd.Series(dict1) we can also use this 

A
a  100
b  200
c  300
d  400
e  800

In [96]:
#Q6:Write a Pandas program to convert a NumPy array to a Pandas series

import numpy as np

array= [10, 20, 30, 40 ,50]

s1=pd.Series(array)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [132]:
#Q7:7. Write a Pandas program to change the data type of given a column or a Series



s1=pd.Series([100,'200','python','300','400'])
print("Before :::",s1.dtypes)


s1=pd.to_numeric(s1,errors='coerce')
print("After :::",s1.dtypes)



Before ::: object
After ::: float64


In [142]:
#Q8:8. Write a Pandas program to convert the first column of a DataFrame as a Series

df = pd.DataFrame({'col1':[1,2,3,4,5],'col2':[4,5,6,7,8],'col3':[12,45,56,32,11]})

s1=df['col1']
print(type(s1))



<class 'pandas.core.series.Series'>


In [153]:
#Q9: Write a Pandas program to convert a given Series to an array

s1= pd.Series([10, 20, 30, 40 ,50])

array=s1.to_numpy()
array


array([10, 20, 30, 40, 50], dtype=int64)

In [172]:
#Q10. Write a Pandas program to convert Series of lists to one Series

s1=pd.Series([['Red', 'Green', 'White'],['Red','Black'],['yellow']])

print('Original Series :')
print(s1)

print('\n')
print('single Series')
s1 = s1.apply(pd.Series).stack().reset_index(drop=True)
s1

Original Series :
0    [Red, Green, White]
1    [Red, Black]       
2    [yellow]           
dtype: object


single Series


0    Red   
1    Green 
2    White 
3    Red   
4    Black 
5    yellow
dtype: object

In [199]:
#Q11. Write a Pandas program to sort a given Series

s1 = pd.Series(['1','3','python','10','5'])

s1.sort_values(ascending=True)


0    1     
3    10    
1    3     
4    5     
2    python
dtype: object

In [217]:
#Q12. Write a Pandas program to add some data to an existing Series

s1 = pd.Series(['1','3','python','10','5'])

s1[5]='22'
s1=s1.append(pd.Series(['php','java']))
s1

0    1     
1    3     
2    python
3    10    
4    5     
5    22    
0    php   
1    java  
dtype: object

In [229]:
#Q13. Write a Pandas program to create a subset of a given series based on value and condition

s1=pd.Series([0,1,2,3,4,5,6,7,8,9,10])

s1=s1.loc[s1 < 7] #getting only first 7 values
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [232]:
#Q14:Write a Pandas program to change the order of index of a given series.

s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print('Original Order')
print(s)

s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Order
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [236]:
#Q15:Write a Pandas program to create the mean and standard deviation of the data of a given Series

s = pd.Series(data = [1,2,3,4,5,6,7,8,9,10])
print(s.mean())
print(s.std())

5.5
3.0276503540974917


In [250]:
#Q16: Write a Pandas program to get the items of a given series not present in another given series


s1=pd.Series([1,2,3,4,5])

s2=pd.Series([11,22,3,4,55])

s1[~s1.isin(s2)]  #  s1 items which are not present in s1:::::: isin

0    1
1    2
4    5
dtype: int64

In [258]:
#Q17. Write a Pandas program to get the items which are not common of two given series

sr1=pd.Series([1,2,3,4,5])

sr2=pd.Series([11,22,3,4,55])

sr11 = pd.Series(np.union1d(sr1, sr2))
sr22 = pd.Series(np.intersect1d(sr1, sr2))
result = sr11[~sr11.isin(sr22)]
print(result)

0    1 
1    2 
4    5 
5    11
6    22
7    55
dtype: int64


In [268]:
#Q18:Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series


s1=pd.Series([3.000938,11.370722,14.612143,8.990256,13.925283,12.056875])
print(s1.describe())

result = np.percentile(s1,q=[0,25,50,75,100])
print(result)

count    6.000000 
mean     10.659370
std      4.247050 
min      3.000938 
25%      9.585373 
50%      11.713798
75%      13.458181
max      14.612143
dtype: float64
[ 3.000938   9.5853725 11.7137985 13.458181  14.612143 ]


In [269]:
#Q19. Write a Pandas program to calculate the frequency counts of each unique value of a given series

s = pd.Series([1,2,3,4,5,1,1,2,3,4,5,6,78,23,45,23,23,22,1,89,90,89])

s.value_counts()

1     4
23    3
2     2
3     2
4     2
5     2
89    2
6     1
78    1
45    1
22    1
90    1
dtype: int64

In [325]:
#Q20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series

s = pd.Series([1,2,3,4,5,1,1,2,3,4,5,6,78,23,45,23,23,22,1,89,90,89,90,90,90,90,90,1,1])

print(s.mode())


s.loc[(s!=1) & (s!=90)] = 'Other' # here first i am getting those rows where value != 1 and then converting all those to "Other" 
s

0    1 
1    90
dtype: int64


0     1    
1     Other
2     Other
3     Other
4     Other
5     1    
6     1    
7     Other
8     Other
9     Other
10    Other
11    Other
12    Other
13    Other
14    Other
15    Other
16    Other
17    Other
18    1    
19    Other
20    90   
21    Other
22    90   
23    90   
24    90   
25    90   
26    90   
27    1    
28    1    
dtype: object

In [331]:
#Q21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

s= pd.Series([1,5,10,3,4,6,7,15,20,43,45])

result= np.where(s%5==0)
print(result)

(array([ 1,  2,  7,  8, 10], dtype=int64),)


In [343]:
#Q22: Write a Pandas program to extract items at given positions of a given series

s= pd.Series([1,5,10,3,4,6,7,15,20,43,45])

s.take([5,10]) # take method used to extract elements from a given index

5     6 
10    45
dtype: int64

In [373]:
#Q23. Write a Pandas program to get the positions of items of a given series in another given series

s1= pd.Series([1,5,10,3,4])

s2= pd.Series([1,11,4,3,23,25,5,23,10])

result=[pd.Index(s2).get_loc(i) for i in s1]  #positions of series 1 elements in series 2


print(result)

[0, 6, 8, 3, 2]


In [368]:
# s= pd.Series([1,5,10,3,4,6,7,15,20,43,45,5])  couple of methods to find the index of a value

# list(s).index(5)

# s[s==5].index[0]

1

In [389]:
#Q24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series

s= pd.Series(['ashutosh','sharma','ankit','kapoor'])

s=s.apply(lambda x:x[0].upper() + x[1:-1] + x[-1].upper() )
s

0    AshutosH
1    SharmA  
2    AnkiT   
3    KapooR  
dtype: object

In [392]:
#Q26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

s=pd.Series([1,3,5,8,10,11,15])

list1=[]

for i in range(0,len(s)-1):
    result=(s[i]-s[i+1])
    list1.append(result)
list1

# or we can also use s.diff() , simple right!!!

[-2, -2, -3, -2, -1, -4]

In [396]:
#Q27. Write a Pandas program to convert a series of date strings to a timeseries

date_series = pd.Series(['11 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06 11:20'])
print("Original Series:")
print(date_series)
print("\nSeries of date strings to a timeseries:")
print(pd.to_datetime(date_series))

Original Series:
0    11 Jan 2015     
1    10-02-2016      
2    20180307        
3    2014/05/06      
4    2016-04-12      
5    2019-04-06 11:20
dtype: object

Series of date strings to a timeseries:
0   2015-01-11 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]


In [406]:
#Q28.Write a Pandas program to get  day of month, day of year, week number and day of week from a given series of date strings

date_series = pd.Series(['11 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06 11:20'])

date_series=pd.to_datetime(date_series)
print(date_series.dt.year)
print(date_series.dt.month)
print(date_series.dt.day_of_year)


0    2015
1    2016
2    2018
3    2014
4    2016
5    2019
dtype: int64
0    1 
1    10
2    3 
3    5 
4    4 
5    4 
dtype: int64
0    11 
1    276
2    66 
3    126
4    103
5    96 
dtype: int64


In [428]:
#Q29. Write a Pandas program to convert year-month string to dates adding a specified day of the month

date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])

date_series=pd.to_datetime(date_series)

date_series



0   2015-01-01
1   2016-02-01
2   2017-03-01
3   2018-04-01
4   2019-05-01
dtype: datetime64[ns]

In [448]:
#Q30. Write a Pandas program to filter words from a given series that contain atleast two vowels
from collections import Counter
series =pd.Series(['Ashutoshe','XXXXX','ZZZZZZ','WWWWWWW','Idiot','Education'])


 
result = series.map(lambda c: sum([Counter(c.lower()).get(i, 0)
                                   for i in list('aeiou')]) >= 2)
 
print(series[result])

0    Ashutoshe
4    Idiot    
5    Education
dtype: object


In [450]:
#Q31. Write a Pandas program to compute the Euclidean distance between two given series.


x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])


print(np.linalg.norm(x-y))

16.492422502470642


In [463]:
#Q32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series

nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

print("\nPositions of the values surrounded by smaller values on both sides:")
temp = np.diff(np.sign(np.diff(nums)))
result = np.where(temp == -2)[0] + 1
print(result)


Positions of the values surrounded by smaller values on both sides:
[1 4 8]


In [476]:
#Q33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character

string1=pd.Series(list('Hello My name is Ashutosh'))

element_freq = string1.value_counts()
current_freq = element_freq.dropna().index[-1]
result = "".join(string1.replace(' ',current_freq))
 
print(result)

HellotMytnametistAshutosh


In [480]:
#Q35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year

result = pd.Series(pd.date_range('2019-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2019:")
print(result)

All Sundays of 2019:
0    2019-01-06
1    2019-01-13
2    2019-01-20
3    2019-01-27
4    2019-02-03
5    2019-02-10
6    2019-02-17
7    2019-02-24
8    2019-03-03
9    2019-03-10
10   2019-03-17
11   2019-03-24
12   2019-03-31
13   2019-04-07
14   2019-04-14
15   2019-04-21
16   2019-04-28
17   2019-05-05
18   2019-05-12
19   2019-05-19
20   2019-05-26
21   2019-06-02
22   2019-06-09
23   2019-06-16
24   2019-06-23
25   2019-06-30
26   2019-07-07
27   2019-07-14
28   2019-07-21
29   2019-07-28
30   2019-08-04
31   2019-08-11
32   2019-08-18
33   2019-08-25
34   2019-09-01
35   2019-09-08
36   2019-09-15
37   2019-09-22
38   2019-09-29
39   2019-10-06
40   2019-10-13
41   2019-10-20
42   2019-10-27
43   2019-11-03
44   2019-11-10
45   2019-11-17
46   2019-11-24
47   2019-12-01
48   2019-12-08
49   2019-12-15
50   2019-12-22
51   2019-12-29
dtype: datetime64[ns]


In [483]:
#Q37. Write a Pandas program to stack two given series vertically and horizontally

series1 = pd.Series(range(10))
series2 = pd.Series(list('pqrstuvwxy'))

df = pd.concat([series1, series2], axis=1)
print("\nStack two given series vertically and horizontally:")
print(df)


Stack two given series vertically and horizontally:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [494]:
#Q39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series

s=pd.Series([3,7,12,88,23,3,1,9,0])

min_s=s.min()
max_s=s.max()

print('Min',s.idxmin())
print('Max',s.idxmax())



Min 8
Max 3
